name: Cygwin Build

on:
  push:
    paths-ignore:
      # ... [unchanged paths-ignore entries]
  pull_request:
    paths-ignore:
      # ... [unchanged paths-ignore entries]
  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: 'windows-latest'

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: bash
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT
          WORKFLOWNAME="${{github.workflow}}"
          NAME_DASHED=${WORKFLOWNAME//+( )/_}
          echo "cache-key=${NAME_DASHED}" >> $GITHUB_OUTPUT

      - uses: cygwin/cygwin-install-action@master
        with:
          packages: cygwin64 gcc-g++=10.2.0-1 ccache python37 python37-future python37-lxml python37-pip python37-setuptools python37-wheel git procps gettext
          add-to-path: false

      - name: setup ccache
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: >-
          mkdir -p /cygdrive/d/a/ardupilot/ardupilot/ccache &&
          mkdir -p /usr/local/etc &&
          echo "export CCACHE_SLOPPINESS=file_stat_matches" >> ~/ccache.conf &&
          echo "export CCACHE_DIR=/cygdrive/d/a/ardupilot/ardupilot/ccache" >> ~/ccache.conf &&
          echo "export CCACHE_BASEDIR=/cygdrive/d/a/ardupilot/ardupilot" >> ~/ccache.conf &&
          echo "export CCACHE_COMPRESS=1" >> ~/ccache.conf &&
          echo "export CCACHE_COMPRESSLEVEL=6" >> ~/ccache.conf &&
          echo "export CCACHE_MAXSIZE=400M" >> ~/ccache.conf &&
          source ~/ccache.conf &&
          ccache -s

      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path: D:/a/ardupilot/ardupilot/ccache
          key: ${{ steps.ccache_cache_timestamp.outputs.cache-key }}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{ steps.ccache_cache_timestamp.outputs.cache-key }}-ccache-  # restore ccache from either previous build on this branch or on base branch

      - name: Prepare Python environment
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: >-
          ln -sf /usr/bin/python3.7 /usr/bin/python && ln -sf /usr/bin/pip3.7 /usr/bin/pip &&
          python -m pip install --progress-bar off empy==3.3.4 pexpect &&
          python -m pip install --progress-bar off dronecan --upgrade &&
          cp /usr/bin/ccache /usr/local/bin/ &&
          cd /usr/local/bin && ln -s ccache /usr/local/bin/gcc &&
          ln -s ccache /usr/local/bin/g++ &&
          ln -s ccache /usr/local/bin/x86_64-pc-cygwin-gcc &&
          ln -s ccache /usr/local/bin/x86_64-pc-cygwin-g++

      - name: List .git directory
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: ls -la .git

      - name: Configure Git safe directory
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: git config --global --add safe.directory /cygdrive/d/a/ardupilotNEW/ardupilotNEW

      - name: Update submodules
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: git submodule update --init --recursive

      - name: Debug information
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: |
          git status
          git rev-parse --is-inside-work-tree
          git submodule status

      - name: Build SITL
        env:
          PATH: /usr/bin:$(cygpath ${SYSTEMROOT})/system32
        shell: C:\cygwin\bin\bash.exe -eo pipefail '{0}'
        run: >-
          export PATH=/usr/local/bin:/usr/bin:$(cygpath ${SYSTEMROOT})/system32 &&
          source ~/ccache.conf &&
          python ./waf configure --board=sitl &&
          python ./waf plane -j8 &&
          ccache -s

      - name: List build directory contents
        run: ls -R build/sitl

      - name: Check build files
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "build/sitl/bin/arduplane"
          fail: true

      - name: Copy build artifact
        run: cp -v build/sitl/bin/arduplane artifacts/ArduPlane.elf.exe

      - name: Archive build
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: artifacts
          retention-days: 7
